{% set version = "0.1.12" %}

package:
  name: docker-image-py
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/d/docker-image-py/docker-image-py-{{ version }}.tar.gz
    sha256: c0eebb6c25714b2a4f91a1462183e70252fa34fb189496d3c54711a64f12f96e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - regex >=2019.4.14

test:
  imports:
    - docker_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/realityone/docker-image-py
  summary: Parse docker image as distribution does.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
