{% set version = "0.2.0" %}

package:
  name: docker-image-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/docker-image-py/docker_image_py-{{ version }}.tar.gz
  sha256: 451ad5b3b656d00797e2b84e7ee2629a01012c52a83439cbcfbdeadc3ead3ae1

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - regex >=2019.4.14

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - docker_image
  commands:
    - pip check

about:
  home: https://github.com/realityone/docker-image-py
  summary: Parse docker image as distribution does.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
