{% set version = "0.1.13" %}

package:
  name: docker-image-py
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/d/docker-image-py/docker_image_py-{{ version }}.tar.gz
    sha256: de2755de0a09c99ae3b4cf42cc470a83b35bfdc4bf8ad66a3d7550d622a8915a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - regex >=2019.4.14

test:
  imports:
    - docker_image
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/realityone/docker-image-py
  summary: Parse docker image as distribution does.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
